import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyWeb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3 className="text-2xl mt-10">Upgrade your web development today</h3>
      </main>
    </div>
  );
}
